"""Bulk-create Epics and Stories from USER_STORIES.md into PMTracker RFP project."""
import sys, os, time
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from pmtracker import api_client

PROJECT_KEY = "RFP"

# ── Epic definitions (12 epics) ──────────────────────────────────────────────

EPICS = [
    {"id": 1, "summary": "RFP Ingestion & Document Management", "description": "Upload, parse, and manage RFP documents with section detection, duplicate prevention, and metadata tagging."},
    {"id": 2, "summary": "Triage & Scope Classification", "description": "Automatically classify RFP sections as In-Scope, Out-of-Scope, or Partial with confidence scoring and technology detection."},
    {"id": 3, "summary": "Clarification / Gap Analysis", "description": "Auto-generate prioritised clarification questions for estimation-critical information gaps."},
    {"id": 4, "summary": "Human-in-the-Loop (HIL) Approval Gate", "description": "Pipeline pause for human review, editing, and approval of generated clarification questions."},
    {"id": 5, "summary": "Client Communication & Response Handling", "description": "Export approved questions, upload client responses, and handle incomplete response loops."},
    {"id": 6, "summary": "Solution Architecture Generation", "description": "Generate cloud-native architecture with Vault differentiators, OOS guardrails, and client answer integration."},
    {"id": 7, "summary": "Estimation & Work Breakdown Structure", "description": "Auto-generate WBS with PERT estimates, velocity benchmarks, contingency, team composition, and pricing model."},
    {"id": 8, "summary": "Final Proposal Generation", "description": "Assemble a complete, professional RFP response document with all 12 sections."},
    {"id": 9, "summary": "The Vault (Knowledge Base Management)", "description": "Ingest, sanitise, tag, and search proprietary knowledge base documents for RAG pipeline."},
    {"id": 10, "summary": "Bid Manager Dashboard", "description": "Dashboard with KPIs, pipeline tracker, real-time progress, and HIL interrupt visibility."},
    {"id": 11, "summary": "Security, IP Protection & Audit", "description": "Agent logging, IP protection, confidentiality defaults, and audit trails for all human decisions."},
    {"id": 12, "summary": "Configuration & DevOps", "description": "Docker Compose, env-based config, Azure OpenAI settings, LangGraph persistence, and standalone CLI tools."},
]

# ── Story definitions (68 stories) ───────────────────────────────────────────

STORIES = [
    # Epic 1 — RFP Ingestion & Document Management
    {"epic": 1, "num": "1.1", "summary": "Upload RFP as PDF or DOCX for automated analysis", "description": "As a Bid Manager, I want to upload an RFP as a PDF or DOCX so that the system can begin automated analysis without me manually copy-pasting content.\n\nAcceptance Criteria:\n- Accepts PDF/DOCX up to 50MB\n- Extracts full text including tables\n- Stores original in S3/MinIO\n- Returns engagement ID immediately"},
    {"epic": 1, "num": "1.2", "summary": "Attach organization name and RFP title at upload", "description": "As a Bid Manager, I want to attach an organization name and RFP title at upload so that the engagement is correctly identified throughout the pipeline.\n\nAcceptance Criteria:\n- Both fields mandatory\n- Title pre-populated from filename\n- Stored in rfp_engagements"},
    {"epic": 1, "num": "1.3", "summary": "Detect and preserve section structure from uploaded document", "description": "As a Bid Manager, I want the system to detect and preserve section structure from the uploaded document so that the triage analysis is granular and section-aware.\n\nAcceptance Criteria:\n- Parser identifies section headers (numbered, uppercase, 'Section X' patterns)\n- Section list visible in triage output"},
    {"epic": 1, "num": "1.4", "summary": "Detect duplicate RFP submissions", "description": "As a Bid Manager, I want duplicate submissions detected so that the same RFP is not processed twice and vector storage is not polluted.\n\nAcceptance Criteria:\n- Checksum (SHA-256) comparison on upload\n- Returns existing engagement ID if match found"},
    {"epic": 1, "num": "1.5", "summary": "Set submission deadline and priority level for engagement", "description": "As a Bid Manager, I want to set a submission deadline and priority level when creating an engagement so that the dashboard can surface urgent bids.\n\nAcceptance Criteria:\n- Priority 1-5 stars\n- Deadline shown with urgency highlighting when <7 days away"},

    # Epic 2 — Triage & Scope Classification
    {"epic": 2, "num": "2.1", "summary": "Auto-classify RFP sections as In-Scope, Out-of-Scope, or Partial", "description": "As a Bid Manager, I want every RFP section automatically classified as In-Scope, Out-of-Scope, or Partial so that I don't spend hours manually reading the full document before deciding whether to bid.\n\nAcceptance Criteria:\n- Every section gets one of: IN_SCOPE, OUT_OF_SCOPE, PARTIAL, REQUIRES_CLARIFICATION\n- Classification shown with colour-coded cards"},
    {"epic": 2, "num": "2.2", "summary": "Hard-block Out-of-Scope sections with referral notes", "description": "As a Bid Manager, I want Out-of-Scope sections hard-blocked and flagged with a referral note so that DPE never inadvertently commits to work it cannot deliver.\n\nAcceptance Criteria:\n- OOS sections cannot be reclassified to IN_SCOPE without human override\n- Referral note populated (e.g., 'Refer to Managed Services practice')"},
    {"epic": 2, "num": "2.3", "summary": "Pre-scan keyword alert before LLM classification", "description": "As a Bid Manager, I want a pre-scan keyword alert before the LLM runs so that obvious OOS content is caught even if the model hallucinates an in-scope classification.\n\nAcceptance Criteria:\n- 16 regex patterns run first\n- Results injected into the LLM prompt as [PRE-SCAN ALERT]\n- Any section whose summary still triggers OOS keywords is automatically demoted to REQUIRES_CLARIFICATION"},
    {"epic": 2, "num": "2.4", "summary": "Triage confidence score and recommended action", "description": "As a Bid Manager, I want a triage confidence score and a recommended action (PROCEED / PARTIAL_PROCEED / REJECT / CLARIFY) so that I can make a go/no-go call in under 2 minutes.\n\nAcceptance Criteria:\n- Score 0-1 displayed as percentage\n- Colour: green >80%, amber 60-80%, red <60%\n- Recommendation displayed prominently"},
    {"epic": 2, "num": "2.5", "summary": "Detect technology stack and business domains from RFP", "description": "As a Bid Manager, I want to see the detected technology stack and business domains from the RFP so that I can quickly assess fit before reading the full triage report.\n\nAcceptance Criteria:\n- Detected tech shown as pills (e.g., 'Spring Boot', 'React')\n- Domains shown in a different colour (e.g., 'Banking', 'Healthcare')"},
    {"epic": 2, "num": "2.6", "summary": "Show in-scope vs OOS breakdown for Partial sections", "description": "As a Bid Manager, I want Partial sections to clearly state which sub-requirements are in-scope vs OOS so that the solution design only covers the deliverable portion.\n\nAcceptance Criteria:\n- Partial cards expandable\n- In-scope portion and OOS exclusion reason both visible"},
    {"epic": 2, "num": "2.7", "summary": "Persist triage result and OOS flags for downstream agents", "description": "As a System, I want the triage result and OOS flags written back to rfp_engagements and triage_results so that every downstream agent can reference the classification without re-running the LLM.\n\nAcceptance Criteria:\n- Structured TriageOutput JSON persisted\n- oos_flagged_sections array on the engagement record"},

    # Epic 3 — Clarification / Gap Analysis
    {"epic": 3, "num": "3.1", "summary": "Auto-generate prioritised clarification questions", "description": "As a Bid Manager, I want the system to automatically generate a prioritised list of clarification questions so that I don't miss estimation-critical information gaps before drafting the solution.\n\nAcceptance Criteria:\n- Max 12 questions\n- Each has: category (SCOPE/TECHNICAL/COMMERCIAL/TIMELINE/INTEGRATION), priority (HIGH/MEDIUM/LOW), and an internal rationale note"},
    {"epic": 3, "num": "3.2", "summary": "Rank clarification questions by priority", "description": "As a Bid Manager, I want questions ranked by priority so that if the client only answers 5, I've captured the most important unknowns first.\n\nAcceptance Criteria:\n- Questions ordered HIGH -> MEDIUM -> LOW\n- Priority badge visible on each card"},
    {"epic": 3, "num": "3.3", "summary": "Include internal rationale for each clarification question", "description": "As a Bid Manager, I want each question to include an internal rationale explaining why that gap blocks estimation so that I can confidently justify the question if the client pushes back.\n\nAcceptance Criteria:\n- Rationale shown in a distinct 'INTERNAL' callout section\n- Not included in the client-facing export"},
    {"epic": 3, "num": "3.4", "summary": "Query The Vault for known estimation gap patterns", "description": "As a System, I want the inquiry agent to query The Vault for known estimation gap patterns so that the questions reflect DPE's accumulated experience, not generic boilerplate.\n\nAcceptance Criteria:\n- Vault query 'common estimation gaps for DPE projects' with min_score 0.65\n- Vault patterns included in the LLM prompt"},
    {"epic": 3, "num": "3.5", "summary": "Exclude OOS-related questions from generated list", "description": "As a Bid Manager, I want questions about Out-of-Scope items automatically excluded from the generated list so that I don't accidentally signal interest in OOS work to the client.\n\nAcceptance Criteria:\n- Post-generation filter removes any question whose text contains OOS category keywords"},

    # Epic 4 — Human-in-the-Loop (HIL) Approval Gate
    {"epic": 4, "num": "4.1", "summary": "Pause pipeline after question generation for human review", "description": "As a Bid Manager, I want the pipeline to pause after question generation so that I can review, edit, approve, or reject each question before it reaches the client.\n\nAcceptance Criteria:\n- LangGraph interrupt fired at hil_gate node\n- Dashboard shows 'Awaiting Review' status\n- No email/notification sent until explicit approval"},
    {"epic": 4, "num": "4.2", "summary": "Edit client-facing text of questions inline", "description": "As a Bid Manager, I want to edit the client-facing text of any question inline so that the tone and wording matches our relationship with that client.\n\nAcceptance Criteria:\n- In-place textarea edit per question\n- Edited version stored in hil_edited_text\n- Original preserved for audit"},
    {"epic": 4, "num": "4.3", "summary": "Approve questions individually (not all-or-nothing)", "description": "As a Bid Manager, I want to approve questions individually so that I can send only the highest-value questions and avoid asking the client for unnecessary information.\n\nAcceptance Criteria:\n- Per-question approve toggle\n- Submit sends only hil_approved = true questions"},
    {"epic": 4, "num": "4.4", "summary": "Log approval actions with name and timestamp", "description": "As a Bid Manager, I want the approval action logged with my name and timestamp so that there is a full audit trail of who approved what.\n\nAcceptance Criteria:\n- hil_reviewed_by and hil_reviewed_at stored in clarification_questions\n- Immutable after submission"},
    {"epic": 4, "num": "4.5", "summary": "Skip HIL gate if all questions rejected", "description": "As a Bid Manager, I want the workflow to proceed directly to solution design if I reject all questions so that low-ambiguity RFPs are not delayed by the HIL gate.\n\nAcceptance Criteria:\n- If zero questions approved, route_after_hil jumps to solution_architect_agent node, bypassing awaiting_client"},

    # Epic 5 — Client Communication & Response Handling
    {"epic": 5, "num": "5.1", "summary": "Export approved questions in clean client-facing format", "description": "As a Bid Manager, I want approved questions exported in a clean, professional format (no internal notes, no rationale) so that the document I send the client looks polished.\n\nAcceptance Criteria:\n- Export uses hil_edited_text if available, else question_text\n- Rationale field excluded\n- Formatted as numbered list"},
    {"epic": 5, "num": "5.2", "summary": "Upload client written responses into platform", "description": "As a Bid Manager, I want to upload the client's written responses directly into the platform so that the Solution Architect Agent has access to those answers when drafting the architecture.\n\nAcceptance Criteria:\n- POST /api/v1/rfp/{id}/client-responses accepts an array of {question_number, client_answer}\n- Resumes LangGraph workflow"},
    {"epic": 5, "num": "5.3", "summary": "Detect incomplete client responses and loop for second inquiry", "description": "As a Bid Manager, I want the system to detect if the client answered fewer than 70% of approved questions and loop back for a second inquiry round so that critical gaps are not silently ignored.\n\nAcceptance Criteria:\n- route_after_client_response checks answered / approved >= 0.7\n- If not, retries inquiry (max 1 retry)"},
    {"epic": 5, "num": "5.4", "summary": "Show unanswered questions for follow-up", "description": "As a Bid Manager, I want to see which questions are still unanswered so that I can follow up with the client on specific items before the solution is drafted.\n\nAcceptance Criteria:\n- Dashboard shows answered/unanswered count per engagement\n- Unanswered questions highlighted in amber"},

    # Epic 6 — Solution Architecture Generation
    {"epic": 6, "num": "6.1", "summary": "Generate complete cloud-native architecture from RFP", "description": "As a Solution Architect, I want the agent to produce a complete cloud-native architecture covering microservices, UI, mobile, and modernisation strategy so that I have a strong first draft to refine.\n\nAcceptance Criteria:\n- Output includes: executive summary, architecture overview, proposed tech stack (per layer), microservices design list, cloud topology, security approach, and a Mermaid.js architecture diagram"},
    {"epic": 6, "num": "6.2", "summary": "Pull Vault differentiators and case studies into solution", "description": "As a Solution Architect, I want the agent to pull relevant differentiators, case studies, and accelerators from The Vault and apply them to the solution so that every proposal references our competitive advantages.\n\nAcceptance Criteria:\n- Vault queried with 3-4 targeted queries (by service line, tech stack, domain, modernisation)\n- Up to 12 deduplicated results fed to the LLM as synthesised context"},
    {"epic": 6, "num": "6.3", "summary": "Confine architecture to in-scope DPE service lines only", "description": "As a Delivery Lead, I want the architecture to be strictly confined to in-scope DPE service lines so that we never commit to work we cannot staff or deliver.\n\nAcceptance Criteria:\n- System prompt hard-blocks OOS services\n- Post-LLM guardrail scrubs any microservice whose name/responsibility contains OOS terms\n- Removed services logged as warnings"},
    {"epic": 6, "num": "6.4", "summary": "Incorporate client clarification answers into architecture", "description": "As a Solution Architect, I want the client's clarification answers incorporated into the architectural decisions so that the design reflects their specific constraints, not generic assumptions.\n\nAcceptance Criteria:\n- All client_answer fields from approved questions injected into the architecture prompt as CLARIFICATION ANSWERS section"},
    {"epic": 6, "num": "6.5", "summary": "Reference Vault content by name only — never reproduce raw text", "description": "As a Solution Architect, I want the agent to reference The Vault's proprietary content by name only (never reproduce raw text) so that our IP is not exposed to the client in verbatim form.\n\nAcceptance Criteria:\n- VaultQueryResult dataclass has no raw_text field by design\n- Agents receive synthesized_insight only\n- vault_references_used stores chunk IDs — never source content"},
    {"epic": 6, "num": "6.6", "summary": "Show which vault assets were referenced in each proposal", "description": "As a Solution Architect, I want to see which vault assets were referenced in each proposal so that I can audit how our IP library is being used.\n\nAcceptance Criteria:\n- differentiators_applied list and vault_references_used ID list persisted in solution_architectures table\n- Visible in the engagement detail view"},

    # Epic 7 — Estimation & Work Breakdown Structure
    {"epic": 7, "num": "7.1", "summary": "Auto-generate WBS from solution architecture", "description": "As a Delivery Lead, I want a detailed WBS automatically generated from the solution architecture so that I don't have to build the estimation spreadsheet from scratch.\n\nAcceptance Criteria:\n- WBS items created per phase (Discovery, Infrastructure, Backend Services, Frontend, Mobile, Integration, DevSecOps, Deployment)\n- One row per microservice/module"},
    {"epic": 7, "num": "7.2", "summary": "PERT three-point estimates per work package", "description": "As a Delivery Lead, I want PERT three-point estimates (best/likely/worst case) per work package so that the final figure reflects real delivery uncertainty.\n\nAcceptance Criteria:\n- All three values captured\n- weighted_days auto-computed as (best + 4*likely + worst) / 6"},
    {"epic": 7, "num": "7.3", "summary": "Apply DPE velocity benchmarks to estimates", "description": "As a Delivery Lead, I want DPE velocity benchmarks applied consistently so that estimates are calibrated to our actual delivery speed, not industry averages.\n\nAcceptance Criteria:\n- Benchmark table in Estimator system prompt (e.g., Spring Boot microservice = 8-15 PD)\n- LLM anchored to these ranges"},
    {"epic": 7, "num": "7.4", "summary": "Apply 15% contingency with clear rationale", "description": "As a Delivery Lead, I want a 15% contingency applied by default with a clear rationale so that proposals are commercially protected from scope creep.\n\nAcceptance Criteria:\n- Contingency configurable (default 15%)\n- subtotal, contingency_usd, and total_usd all shown separately in the commercial summary"},
    {"epic": 7, "num": "7.5", "summary": "Output team composition (roles x headcount)", "description": "As a Delivery Lead, I want a team composition output so that I can cross-check the proposed team against available bench capacity.\n\nAcceptance Criteria:\n- team_composition dict (e.g., {'Java Lead': 2, 'React Dev': 3, 'Architect': 1, 'PM': 1}) stored on commercial_summary"},
    {"epic": 7, "num": "7.6", "summary": "Recommend pricing model based on total effort", "description": "As a Delivery Lead, I want the pricing model recommendation (Fixed Price / T&M / Hybrid) based on total effort so that the commercial structure matches the engagement risk profile.\n\nAcceptance Criteria:\n- Logic: <1500 PD -> FIXED_PRICE, >1500 PD -> T_AND_M, ambiguous -> HYBRID\n- Documented in estimator prompt"},
    {"epic": 7, "num": "7.7", "summary": "Explicitly exclude Manual Testing and Production Support from WBS", "description": "As a Delivery Lead, I want Manual Testing and Production Support explicitly excluded from the WBS so that the estimate never inflates scope with OOS labour.\n\nAcceptance Criteria:\n- Estimator prompt explicitly labels Phase 7 as 'developer testing only' with a hard note that 'manual/UAT testing is OOS'"},

    # Epic 8 — Final Proposal Generation
    {"epic": 8, "num": "8.1", "summary": "Assemble complete 12-section RFP response document", "description": "As a Bid Manager, I want the system to assemble a complete, professionally written RFP response document so that I receive a near-ready proposal with minimal manual editing.\n\nAcceptance Criteria:\n- 12-section document: Cover Letter, ToC, Executive Summary, Requirements Understanding, Scope of Work, Architecture, Delivery Approach, Team, Timeline, Investment, Why DPE, WBS Appendix"},
    {"epic": 8, "num": "8.2", "summary": "Call out OOS items in Scope of Work with referral notes", "description": "As a Bid Manager, I want OOS items explicitly called out in the Scope of Work section with a referral note so that the client is formally informed of what is excluded.\n\nAcceptance Criteria:\n- Each OOS section appears as: '[Section X] — Outside DPE Scope. Recommend referral to [practice].'"},
    {"epic": 8, "num": "8.3", "summary": "Authoritative client-outcome-focused tone in proposal", "description": "As a Bid Manager, I want the tone to be authoritative and client-outcome focused, not generic vendor boilerplate, so that the proposal reflects the voice of a market leader.\n\nAcceptance Criteria:\n- Response Writer system prompt bans filler phrases\n- Each differentiator cited with an anonymised outcome metric"},
    {"epic": 8, "num": "8.4", "summary": "Present commercial totals without exposing internal rates", "description": "As a Bid Manager, I want the commercial investment section to present totals cleanly without exposing internal day rates or pricing model mechanics so that margin information is protected.\n\nAcceptance Criteria:\n- Proposal shows total investment and milestone structure\n- Daily rates and blended rate NOT included in the client-facing output"},
    {"epic": 8, "num": "8.5", "summary": "Export final proposal as Markdown", "description": "As a Bid Manager, I want the final proposal exported as Markdown (convertible to DOCX/PDF) so that I can apply the company template before sending.\n\nAcceptance Criteria:\n- final_proposal_text stored in state and retrievable via GET /api/v1/rfp/{id}/proposal"},

    # Epic 9 — The Vault
    {"epic": 9, "num": "9.1", "summary": "Ingest vault documents from categorised subfolders via CLI", "description": "As a Vault Admin, I want to drop PDF/DOCX/TXT files into categorised subfolders and trigger a single command to ingest them all so that populating the knowledge base requires no coding.\n\nAcceptance Criteria:\n- python scripts/ingest_vault.py scans vault_docs/{case_studies,differentiators,tech_accelerators,methodologies,pricing_models}/\n- Progress table printed per file"},
    {"epic": 9, "num": "9.2", "summary": "Auto-sanitise vault documents of PII and client names", "description": "As a Vault Admin, I want uploaded files automatically sanitised of client names, project names, person names, dollar amounts, and PII before any content is stored.\n\nAcceptance Criteria:\n- Pass 1: 8 regex rules (emails, phones, $ amounts, dates, internal URLs, project codes)\n- Pass 2: LLM rewrites proper nouns to industry descriptors\n- Sanitization change count reported per file"},
    {"epic": 9, "num": "9.3", "summary": "Auto-extract service lines, technologies, and industries metadata", "description": "As a Vault Admin, I want service lines, technologies, and industries automatically extracted from each document so that I don't have to manually tag every file.\n\nAcceptance Criteria:\n- LLM metadata extraction runs on the first 3000 chars of each document\n- Fields can be overridden via CLI --service-lines flag or API form fields"},
    {"epic": 9, "num": "9.4", "summary": "Skip already-processed files on re-ingestion", "description": "As a Vault Admin, I want re-running the ingestion to skip already-processed files so that I can add new documents to the folder without reprocessing the entire library.\n\nAcceptance Criteria:\n- Checksum-based dedup: {doc_id}__chunk_0000 existence checked in Pinecone before processing\n- 'Already ingested' reported in the summary table"},
    {"epic": 9, "num": "9.5", "summary": "Ingest single file via API upload", "description": "As a Vault Admin, I want to ingest a single file via API upload without running the CLI so that new assets can be added from the dashboard while the system is running.\n\nAcceptance Criteria:\n- POST /api/v1/vault/ingest/file multipart form\n- Returns chunks_stored and sanitization_changes"},
    {"epic": 9, "num": "9.6", "summary": "Search vault with metadata-only results", "description": "As a Vault Admin, I want to search the vault and see metadata-only results (titles, categories, relevance scores, synthesised insights) so that I can verify the quality of retrieval without exposing stored content.\n\nAcceptance Criteria:\n- GET /api/v1/vault/search?query=... returns VaultQueryResult objects — no raw_text field\n- Score, title, service_lines, synthesised_insight shown"},
    {"epic": 9, "num": "9.7", "summary": "View vault vector count and category breakdown", "description": "As a Vault Admin, I want to see total vector count and category breakdown in the Pinecone index so that I know how healthy and populated the knowledge base is.\n\nAcceptance Criteria:\n- GET /api/v1/vault/stats calls index.describe_index_stats()\n- Returns total vectors and namespace breakdown"},
    {"epic": 9, "num": "9.8", "summary": "Store vault chunks with confidentiality and summary metadata", "description": "As a System, I want vault chunks stored with is_confidential: true, description_summary, key_outcomes, and applicable_scenarios metadata so that agents can make relevance decisions without reading raw text.\n\nAcceptance Criteria:\n- All five metadata fields populated on every upserted vector\n- raw_text deliberately absent from the Pinecone metadata schema"},

    # Epic 10 — Bid Manager Dashboard
    {"epic": 10, "num": "10.1", "summary": "Dashboard showing all active engagements with status and deadline", "description": "As a Bid Manager, I want a single dashboard showing all active engagements with status, deadline, and pipeline value so that I can manage my entire bid portfolio at a glance.\n\nAcceptance Criteria:\n- Table with: Priority stars, Title/Client, Status badge, Deadline, Value (TBD until estimated), Action button\n- Filterable by status"},
    {"epic": 10, "num": "10.2", "summary": "KPI bar showing Active, Action Required, Response Ready, Pipeline Value", "description": "As a Bid Manager, I want a KPI bar at the top showing Active Engagements, Action Required, Response Ready, and Pipeline Value so that the most important numbers are always visible.\n\nAcceptance Criteria:\n- KPI bar updates on navigation\n- 'Action Required' highlighted amber when >0\n- Pipeline Value sums all estimated total_usd values"},
    {"epic": 10, "num": "10.3", "summary": "Real-time progress updates via WebSocket", "description": "As a Bid Manager, I want real-time progress updates as each agent runs so that I don't have to refresh the page to know where the pipeline is.\n\nAcceptance Criteria:\n- WebSocket connection per engagement\n- Events pushed as each agent completes\n- Event log displayed in a scrollable terminal-style panel"},
    {"epic": 10, "num": "10.4", "summary": "Visual 7-stage pipeline tracker", "description": "As a Bid Manager, I want a visual pipeline tracker showing all 7 stages (Triage -> Inquiry -> HIL Review -> Awaiting Client -> Architecture -> Estimation -> Writing) with clear active/complete/pending states.\n\nAcceptance Criteria:\n- Step indicators with colour: green (complete), blue (active), amber (HIL/client wait), grey (pending)\n- Connector lines between steps"},
    {"epic": 10, "num": "10.5", "summary": "Highlight HIL interrupt points distinctly on dashboard", "description": "As a Bid Manager, I want the dashboard to highlight the two HIL interrupt points distinctly from automated steps so that I never miss an action that is waiting on me.\n\nAcceptance Criteria:\n- HIL steps shown in amber with user prefix\n- 'Awaiting Review' badge shown\n- Dashboard KPI increments 'Action Required' counter"},
    {"epic": 10, "num": "10.6", "summary": "Display rejection banner with triage reason for rejected RFPs", "description": "As a Bid Manager, I want rejected RFPs to display a clear rejection banner with the triage reason so that I can record why we chose not to bid and communicate this to stakeholders.\n\nAcceptance Criteria:\n- Red banner on rejected engagements showing OOS section count and recommended_action from triage\n- Engagement frozen — no further pipeline steps available"},

    # Epic 11 — Security, IP Protection & Audit
    {"epic": 11, "num": "11.1", "summary": "Log every agent invocation with input/output and metrics", "description": "As a Delivery Lead, I want every agent invocation logged with input/output snapshots, token counts, duration, and vault chunks used so that I can audit cost and quality retroactively.\n\nAcceptance Criteria:\n- agent_run_logs table populated after every agent\n- Input/output snapshots sanitised (no vault raw text)\n- Queryable by engagement or agent name"},
    {"epic": 11, "num": "11.2", "summary": "Prevent raw vault content from appearing in prompts or responses", "description": "As a Delivery Lead, I want the system to prevent raw vault content from ever appearing in agent prompts or API responses so that our proprietary IP cannot be extracted via the RFP response.\n\nAcceptance Criteria:\n- Structural enforcement: VaultQueryResult has no raw_text field\n- vault_references_used stores chunk IDs only\n- Agents receive synthesized_insight summaries"},
    {"epic": 11, "num": "11.3", "summary": "Default all vault documents to is_confidential: true", "description": "As a Vault Admin, I want all vault documents marked is_confidential: true by default so that a misconfigured query cannot accidentally expose source content.\n\nAcceptance Criteria:\n- Default True in VaultDocument dataclass and VaultIngestionService._embed_and_store\n- Cannot be set to False via the API without an explicit admin override"},
    {"epic": 11, "num": "11.4", "summary": "Timestamp and attribute all HIL approvals and client uploads", "description": "As a Delivery Lead, I want HIL approvals and client response uploads to be timestamped and attributed to a named user so that there is a non-repudiable audit trail for every human decision.\n\nAcceptance Criteria:\n- hil_reviewed_by, hil_reviewed_at, client_answered_at stored in clarification_questions\n- Cannot be overwritten after initial write"},
    {"epic": 11, "num": "11.5", "summary": "Never include internal rate cards in final proposal", "description": "As a Bid Manager, I want the final proposal to never contain internal rate cards, blended day rates, or pricing model mechanics so that margin information is protected from the client.\n\nAcceptance Criteria:\n- Response Writer system prompt explicitly instructs: 'Do NOT reveal internal rates.'\n- daily_rate_usd fields from WBS excluded from the user-facing proposal section"},

    # Epic 12 — Configuration & DevOps
    {"epic": 12, "num": "12.1", "summary": "Single docker-compose up for full local environment", "description": "As a Developer, I want a single docker-compose up to spin up the full local environment (API, React UI, PostgreSQL, MinIO) so that onboarding takes minutes, not hours.\n\nAcceptance Criteria:\n- Five services defined: backend, frontend, postgres, minio, adminer\n- schema.sql auto-applied on first run"},
    {"epic": 12, "num": "12.2", "summary": "Manage all credentials via .env file", "description": "As a Developer, I want all credentials and configuration managed via a .env file so that secrets are never hard-coded in source.\n\nAcceptance Criteria:\n- .env.example documents all required variables\n- Pydantic Settings class reads from environment\n- lru_cache prevents repeated disk reads"},
    {"epic": 12, "num": "12.3", "summary": "Independently configurable Azure OpenAI deployment settings", "description": "As a Developer, I want the Azure OpenAI deployment name, endpoint, and API version independently configurable so that I can point the same codebase at different Azure deployments for dev/staging/production without code changes.\n\nAcceptance Criteria:\n- Five distinct env vars: AZURE_OPENAI_API_KEY, AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_VERSION, AZURE_OPENAI_DEPLOYMENT_NAME, AZURE_OPENAI_EMBEDDING_DEPLOYMENT"},
    {"epic": 12, "num": "12.4", "summary": "Persist LangGraph workflow state in PostgreSQL", "description": "As a Developer, I want the LangGraph workflow state persisted in PostgreSQL so that a server restart does not lose in-flight engagement progress and HIL interrupts survive process restarts.\n\nAcceptance Criteria:\n- AsyncPostgresSaver configured as LangGraph checkpointer\n- State restorable by engagement_id"},
    {"epic": 12, "num": "12.5", "summary": "Run vault ingestion CLI independently of API server", "description": "As a Developer, I want the vault ingestion CLI to be runnable independently of the API server so that the knowledge base can be pre-populated during CI/CD or before go-live without the full stack running.\n\nAcceptance Criteria:\n- python scripts/ingest_vault.py loads .env directly via python-dotenv\n- No FastAPI dependency"},
]

print(f"Defined {len(EPICS)} epics and {len(STORIES)} stories")

# ── Step 1: Create Epics ─────────────────────────────────────────────────────
epic_keys = {}  # epic_id -> issue_key

print("\n=== Creating Epics ===")
for epic in EPICS:
    result = api_client.post("/issues", {
        "project_key": PROJECT_KEY,
        "summary": f"Epic {epic['id']}: {epic['summary']}",
        "issue_type": "Epic",
        "description": epic["description"],
        "priority": "High",
        "labels": [f"epic-{epic['id']}"],
    })
    key = result.get("key", "?")
    epic_keys[epic["id"]] = key
    print(f"  Created {key} — {epic['summary']}")
    time.sleep(0.3)

print(f"\nEpic keys: {epic_keys}")

# ── Step 2: Create Stories and link to Epics ─────────────────────────────────
print("\n=== Creating Stories ===")
created_count = 0
for story in STORIES:
    epic_key = epic_keys.get(story["epic"])
    result = api_client.post("/issues", {
        "project_key": PROJECT_KEY,
        "summary": f"[{story['num']}] {story['summary']}",
        "issue_type": "Story",
        "description": story["description"],
        "priority": "Medium",
        "labels": [f"epic-{story['epic']}"],
        "epic_link": epic_key,
    })
    key = result.get("key", "?")
    created_count += 1
    print(f"  [{created_count}/68] {key} — [{story['num']}] {story['summary'][:60]}... -> {epic_key}")
    time.sleep(0.2)

print(f"\n=== Done! Created {len(epic_keys)} epics + {created_count} stories in project {PROJECT_KEY} ===")
